-- CreateTable
CREATE TABLE "bet_data" (
    "id" SERIAL NOT NULL,
    "user_uuid" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "game_type" INTEGER NOT NULL,
    "bet_type" INTEGER NOT NULL,
    "bet_category" TEXT NOT NULL,
    "number" TEXT[],
    "amount" INTEGER NOT NULL,
    "price" INTEGER NOT NULL,
    "point" INTEGER NOT NULL,
    "status" INTEGER NOT NULL,
    "result" INTEGER NOT NULL,
    "payout" INTEGER NOT NULL,
    "term" TEXT NOT NULL,
    "term_timestamp" BIGINT NOT NULL,
    "ticket_id" INTEGER NOT NULL,
    "source" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "extra_price_agent_default" INTEGER NOT NULL,
    "extra_price_master_default" INTEGER NOT NULL,
    "extra_price_super_default" INTEGER NOT NULL,
    "extra_price_exchange_default" INTEGER NOT NULL,
    "extra_price_admin_default" INTEGER NOT NULL,
    "extra_price_point" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "bet_data_pkey" PRIMARY KEY ("id")
);
